// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// analyze_transcript_java_exact
List analyze_transcript_java_exact(List transcript_info, List bam_data, int intron_flank_threshold, bool consider_exon_in_intron);
RcppExport SEXP _intronOrder_analyze_transcript_java_exact(SEXP transcript_infoSEXP, SEXP bam_dataSEXP, SEXP intron_flank_thresholdSEXP, SEXP consider_exon_in_intronSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type transcript_info(transcript_infoSEXP);
    Rcpp::traits::input_parameter< List >::type bam_data(bam_dataSEXP);
    Rcpp::traits::input_parameter< int >::type intron_flank_threshold(intron_flank_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type consider_exon_in_intron(consider_exon_in_intronSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_transcript_java_exact(transcript_info, bam_data, intron_flank_threshold, consider_exon_in_intron));
    return rcpp_result_gen;
END_RCPP
}
// analyze_transcript_java_exact_debug
List analyze_transcript_java_exact_debug(List transcript_info, List bam_data, int intron_flank_threshold, bool consider_exon_in_intron);
RcppExport SEXP _intronOrder_analyze_transcript_java_exact_debug(SEXP transcript_infoSEXP, SEXP bam_dataSEXP, SEXP intron_flank_thresholdSEXP, SEXP consider_exon_in_intronSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type transcript_info(transcript_infoSEXP);
    Rcpp::traits::input_parameter< List >::type bam_data(bam_dataSEXP);
    Rcpp::traits::input_parameter< int >::type intron_flank_threshold(intron_flank_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type consider_exon_in_intron(consider_exon_in_intronSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_transcript_java_exact_debug(transcript_info, bam_data, intron_flank_threshold, consider_exon_in_intron));
    return rcpp_result_gen;
END_RCPP
}
// test_coverage_logic_debug
List test_coverage_logic_debug(int read_start, int read_end, int left_exon_end, int right_exon_start, int intron_flank_threshold, bool consider_exon_in_intron);
RcppExport SEXP _intronOrder_test_coverage_logic_debug(SEXP read_startSEXP, SEXP read_endSEXP, SEXP left_exon_endSEXP, SEXP right_exon_startSEXP, SEXP intron_flank_thresholdSEXP, SEXP consider_exon_in_intronSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type read_start(read_startSEXP);
    Rcpp::traits::input_parameter< int >::type read_end(read_endSEXP);
    Rcpp::traits::input_parameter< int >::type left_exon_end(left_exon_endSEXP);
    Rcpp::traits::input_parameter< int >::type right_exon_start(right_exon_startSEXP);
    Rcpp::traits::input_parameter< int >::type intron_flank_threshold(intron_flank_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type consider_exon_in_intron(consider_exon_in_intronSEXP);
    rcpp_result_gen = Rcpp::wrap(test_coverage_logic_debug(read_start, read_end, left_exon_end, right_exon_start, intron_flank_threshold, consider_exon_in_intron));
    return rcpp_result_gen;
END_RCPP
}
// test_debug_output
List test_debug_output();
RcppExport SEXP _intronOrder_test_debug_output() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_debug_output());
    return rcpp_result_gen;
END_RCPP
}
// analyze_multiple_transcripts
List analyze_multiple_transcripts(List transcript_list, List bam_data_list, int intron_flank_threshold, bool consider_exon_in_intron);
RcppExport SEXP _intronOrder_analyze_multiple_transcripts(SEXP transcript_listSEXP, SEXP bam_data_listSEXP, SEXP intron_flank_thresholdSEXP, SEXP consider_exon_in_intronSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type transcript_list(transcript_listSEXP);
    Rcpp::traits::input_parameter< List >::type bam_data_list(bam_data_listSEXP);
    Rcpp::traits::input_parameter< int >::type intron_flank_threshold(intron_flank_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type consider_exon_in_intron(consider_exon_in_intronSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_multiple_transcripts(transcript_list, bam_data_list, intron_flank_threshold, consider_exon_in_intron));
    return rcpp_result_gen;
END_RCPP
}
// find_opti_dynam_r_cpp_bit
List find_opti_dynam_r_cpp_bit(NumericMatrix t_read_count_mat, double t_alpha_v);
RcppExport SEXP _intronOrder_find_opti_dynam_r_cpp_bit(SEXP t_read_count_matSEXP, SEXP t_alpha_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t_read_count_mat(t_read_count_matSEXP);
    Rcpp::traits::input_parameter< double >::type t_alpha_v(t_alpha_vSEXP);
    rcpp_result_gen = Rcpp::wrap(find_opti_dynam_r_cpp_bit(t_read_count_mat, t_alpha_v));
    return rcpp_result_gen;
END_RCPP
}
// find_best_order_full2_c
List find_best_order_full2_c(NumericMatrix t_read_count_mat, double t_alpha_v);
RcppExport SEXP _intronOrder_find_best_order_full2_c(SEXP t_read_count_matSEXP, SEXP t_alpha_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t_read_count_mat(t_read_count_matSEXP);
    Rcpp::traits::input_parameter< double >::type t_alpha_v(t_alpha_vSEXP);
    rcpp_result_gen = Rcpp::wrap(find_best_order_full2_c(t_read_count_mat, t_alpha_v));
    return rcpp_result_gen;
END_RCPP
}
// hill_c
List hill_c(NumericMatrix t_read_count_mat, double t_alpha_v);
RcppExport SEXP _intronOrder_hill_c(SEXP t_read_count_matSEXP, SEXP t_alpha_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t_read_count_mat(t_read_count_matSEXP);
    Rcpp::traits::input_parameter< double >::type t_alpha_v(t_alpha_vSEXP);
    rcpp_result_gen = Rcpp::wrap(hill_c(t_read_count_mat, t_alpha_v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intronOrder_analyze_transcript_java_exact", (DL_FUNC) &_intronOrder_analyze_transcript_java_exact, 4},
    {"_intronOrder_analyze_transcript_java_exact_debug", (DL_FUNC) &_intronOrder_analyze_transcript_java_exact_debug, 4},
    {"_intronOrder_test_coverage_logic_debug", (DL_FUNC) &_intronOrder_test_coverage_logic_debug, 6},
    {"_intronOrder_test_debug_output", (DL_FUNC) &_intronOrder_test_debug_output, 0},
    {"_intronOrder_analyze_multiple_transcripts", (DL_FUNC) &_intronOrder_analyze_multiple_transcripts, 4},
    {"_intronOrder_find_opti_dynam_r_cpp_bit", (DL_FUNC) &_intronOrder_find_opti_dynam_r_cpp_bit, 2},
    {"_intronOrder_find_best_order_full2_c", (DL_FUNC) &_intronOrder_find_best_order_full2_c, 2},
    {"_intronOrder_hill_c", (DL_FUNC) &_intronOrder_hill_c, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_intronOrder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
