# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

analyze_transcript_java_exact <- function(transcript_info, bam_data, intron_flank_threshold = 90L, consider_exon_in_intron = TRUE) {
    .Call('_intronOrder_analyze_transcript_java_exact', PACKAGE = 'intronOrder', transcript_info, bam_data, intron_flank_threshold, consider_exon_in_intron)
}

analyze_transcript_java_exact_debug <- function(transcript_info, bam_data, intron_flank_threshold = 90L, consider_exon_in_intron = TRUE) {
    .Call('_intronOrder_analyze_transcript_java_exact_debug', PACKAGE = 'intronOrder', transcript_info, bam_data, intron_flank_threshold, consider_exon_in_intron)
}

test_coverage_logic_debug <- function(read_start, read_end, left_exon_end, right_exon_start, intron_flank_threshold, consider_exon_in_intron) {
    .Call('_intronOrder_test_coverage_logic_debug', PACKAGE = 'intronOrder', read_start, read_end, left_exon_end, right_exon_start, intron_flank_threshold, consider_exon_in_intron)
}

test_debug_output <- function() {
    .Call('_intronOrder_test_debug_output', PACKAGE = 'intronOrder')
}

analyze_multiple_transcripts <- function(transcript_list, bam_data_list, intron_flank_threshold = 90L, consider_exon_in_intron = TRUE) {
    .Call('_intronOrder_analyze_multiple_transcripts', PACKAGE = 'intronOrder', transcript_list, bam_data_list, intron_flank_threshold, consider_exon_in_intron)
}

find_opti_dynam_r_cpp_bit <- function(t_read_count_mat, t_alpha_v = 0.1) {
    .Call('_intronOrder_find_opti_dynam_r_cpp_bit', PACKAGE = 'intronOrder', t_read_count_mat, t_alpha_v)
}

find_best_order_full2_c <- function(t_read_count_mat, t_alpha_v = 0.1) {
    .Call('_intronOrder_find_best_order_full2_c', PACKAGE = 'intronOrder', t_read_count_mat, t_alpha_v)
}

hill_c <- function(t_read_count_mat, t_alpha_v = 0.1) {
    .Call('_intronOrder_hill_c', PACKAGE = 'intronOrder', t_read_count_mat, t_alpha_v)
}

